//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by fitask. DO NOT EDIT.

package scalewaytasks

import (
	"k8s.io/kops/upup/pkg/fi"
)

// InstanceScalingGroup

var _ fi.HasLifecycle = (*InstanceScalingGroup)(nil)

func (o *InstanceScalingGroup) GetLifecycle() fi.Lifecycle {
	return o.Lifecycle
}

func (o *InstanceScalingGroup) SetLifecycle(lifecycle fi.Lifecycle) {
	o.Lifecycle = lifecycle
}

var _ fi.HasName = (*InstanceScalingGroup)(nil)

func (o *InstanceScalingGroup) GetName() *string {
	return o.Name
}

func (o *InstanceScalingGroup) String() string {
	return fi.CloudupTaskAsString(o)
}
