//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by fitask. DO NOT EDIT.

package scalewaytasks

import (
	"k8s.io/kops/upup/pkg/fi"
)

// InstanceTemplate

var _ fi.HasLifecycle = (*InstanceTemplate)(nil)

func (o *InstanceTemplate) GetLifecycle() fi.Lifecycle {
	return o.Lifecycle
}

func (o *InstanceTemplate) SetLifecycle(lifecycle fi.Lifecycle) {
	o.Lifecycle = lifecycle
}

var _ fi.HasName = (*InstanceTemplate)(nil)

func (o *InstanceTemplate) GetName() *string {
	return o.Name
}

func (o *InstanceTemplate) String() string {
	return fi.CloudupTaskAsString(o)
}
